plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.78'
}

version = "$minecraft_version-$mod_version"
base {
    archivesName = project.name
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    // withJavadocJar()
}

legacyForge {
    version = project.forge_version

    parchment {
        minecraftVersion = project.parchment_minecraft_version
        mappingsVersion = project.parchment_mappings_version
    }

    // Validate AT files and raise errors when they have invalid targets
    // This option is false by default, but turning it on is recommended
    validateAccessTransformers = true

    runs {
        configureEach {
            // Separate working directory of each runs
            gameDirectory = project.file("runs/$name")

            // log4j2 bug fix
            systemProperty 'log4j2.formatMsgNoLookups', 'true'

            // mixin
            systemProperty 'mixin.debug.verbose', 'true'
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'mixin.checks', 'true'
            systemProperty 'mixin.dumpTargetOnFailure', 'true'
            systemProperty 'mixin.hotSwap', 'true'

            // Recommended logging data for a userdev environment
            // Added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '-nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "$mod_id" {
            sourceSet sourceSets.main
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.forge.mixins.json"
}

// /////////////////////////////
// ////////// CAUTION //////////
// /////////////////////////////
// Based on the operating mode of the ParchmentMC plugin,
// repositories containing dependencies requiring deobfuscation cannot be declared as exclusive.
// Just using content filter instead.
repositories {
    mavenCentral()
    maven {
        name 'Curse Maven'
        url 'https://cursemaven.com'
        content { includeGroup 'curse.maven' }
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }
    maven {
        name 'BlameJared'
        url 'https://maven.blamejared.com'
    }
    maven {
        // JEI since January 2023
        name 'Jared\'s maven'
        url 'https://maven.blamejared.com/mezz/jei/'
    }
    maven {
        // JEI fallback
        name 'ModMaven'
        url 'https://modmaven.k-4u.nl'
    }
    maven {
        // Architectury, Cloth Config, REI
        name 'Shedaniel\'s maven'
        url 'https://maven.shedaniel.me/'
        content {
            includeGroup 'me.shedaniel'
            includeGroup 'me.shedaniel.cloth'
            includeGroup 'dev.architectury'
        }
    }
    maven {
        // WAILA, WTHIT
        url 'https://maven2.bai.lol'
        content {
            includeGroup 'mcp.mobius.waila'
            includeGroup 'lol.bai'
        }
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:24.1.0'

    // //////////// mixin ////////////
    annotationProcessor "org.spongepowered:mixin:$mixin_version:processor"
    testAnnotationProcessor "org.spongepowered:mixin:$mixin_version:processor"

    // //////////// enough items ////////////
    modCompileOnly "mezz.jei:$jei_artifact_id-common-api:$jei_version"
    modCompileOnly "mezz.jei:$jei_artifact_id-forge-api:$jei_version"

    // Always depend on the REI API to compile
    switch (project.runtime_variants_enough_items) {
        case 'jei': {
            modRuntimeOnly "mezz.jei:$jei_artifact_id-forge:$jei_version"

            compileOnly 'me.shedaniel.cloth:basic-math:0.6.1'
            modCompileOnly "dev.architectury:architectury-forge:$architectury_version"
            modCompileOnly "me.shedaniel.cloth:cloth-config-forge:$cloth_config_version"
            modCompileOnly "me.shedaniel:RoughlyEnoughItems-forge:$rei_version"

            break
        }
        case 'rei': {
            implementation 'me.shedaniel.cloth:basic-math:0.6.1'
            modImplementation "dev.architectury:architectury-forge:$architectury_version"
            modImplementation "me.shedaniel.cloth:cloth-config-forge:$cloth_config_version"
            modImplementation "me.shedaniel:RoughlyEnoughItems-forge:$rei_version"

            break
        }
        default: {
            modCompileOnly "dev.architectury:architectury-forge:$architectury_version"
            modCompileOnly "me.shedaniel.cloth:cloth-config-forge:$cloth_config_version"
            modCompileOnly "me.shedaniel:RoughlyEnoughItems-forge:$rei_version"

            break
        }
    }

    // //////////// looking tooltip (Jade / WTHIT / TOP) ////////////
    // jade
    if (project.runtime_variants_looking_tooltip == 'jade') {
        modImplementation "curse.maven:jade-324717:$jade_version"
    } else {
        modCompileOnly "curse.maven:jade-324717:$jade_version"
    }

    // wthit
    if (project.runtime_variants_looking_tooltip == 'wthit') {
        modRuntimeOnly "mcp.mobius.waila:wthit:forge-$wthit_version"
        modRuntimeOnly "lol.bai:badpackets:forge-$badpackets_version"
    } else {
        modCompileOnly "mcp.mobius.waila:wthit-api:forge-$wthit_version"
    }

    // top
    if (project.runtime_variants_looking_tooltip == 'top') {
        modImplementation "curse.maven:the-one-probe-245211:$top_version"
    } else {
        compileOnly "curse.maven:the-one-probe-245211:$top_version"
    }

    // //////////// QoL ////////////
    modRuntimeOnly "curse.maven:catalogue-459701:$catalogue_version"

    modRuntimeOnly "curse.maven:configured-457570:$configured_version"

    modRuntimeOnly "curse.maven:searchables-858542:$searchables_version"
    modRuntimeOnly "curse.maven:controlling-250398:$controlling_version"

    modRuntimeOnly "curse.maven:spark-361579:$spark_version"

    modRuntimeOnly "curse.maven:XaeroMinimap-263420:$xaerominimap_version"
    modRuntimeOnly "curse.maven:XaeroWorldmap-317780:$xaeroworldmap_version"
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources/' }

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
def filter = ['pack.mcmeta', '*.mixins.json', 'META-INF/mods.toml']
def expandProps = [
        'version': version,
        'group': project.group, //Else we target the task's group.
        'mod_id': mod_id,
        'mod_name': mod_name,
        'description': project.description,
        'license': license,
        'credits': credits,
        'author': author,
        'resourcepack_format': resourcepack_format,
        'datapack_format': datapack_format,

        'java_version': java_version,
        'mixin_version': mixin_version,
        'minecraft_version': minecraft_version,
        'forge_version': forge_version,

        'minecraft_request': minecraft_request,
        'fml_request': fml_request,
        'forge_request': forge_request,
]
static void expandPropsToResources(ProcessResources task, Iterable<String> resourceFilter, Map<String, ?> props) {
    task.duplicatesStrategy = DuplicatesStrategy.INCLUDE
    task.filesMatching(resourceFilter) {
        expand props
    }
    task.inputs.properties props
}
tasks.withType(ProcessResources).configureEach {
    expandPropsToResources(it, filter, expandProps)
}

tasks.withType(JavaCompile).configureEach {
    options.release = Integer.parseInt(java_version)
    options.encoding = 'UTF-8'
    options.deprecation = false
}

static void eachLicences(Project project, Closure<?> closure) {
    project.fileTree(dir: project.rootDir, include: 'LICENSE*')
            .files.each { closure(it) }
}

tasks.named('sourcesJar') {
    eachLicences(rootProject) { File file ->
        jar.from(file)
    }
}

// Example for how to get properties into the manifest for reading by the runtime..
tasks.named('jar', Jar) {
    eachLicences(rootProject) { File file ->
        jar.from(file)
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : author,
                'Specification-Version' : '1', // We are version 1 of ourselves
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : author,
                'Built-On-Minecraft'    : minecraft_version,
                'Implementation-Timestamp': new Date().format('yyyy-MM-dd\'T\'HH:mm:ssZ'),
                'MixinConfigs': "${mod_id}.forge.mixins.json",
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            name = "Local"
            // url System.getenv("local_maven_url")
            url = file('build/repo').toURI()
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
