# ###################
# Gradle Properties
# ###################
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true

# Uncomment it if you want to know the details of build process.
# More recommended to set it locally rather than project sharing.
#org.gradle.logging.level=info

# Uncomment it if you want the console to look prettier.
# More recommended to set it locally rather than project sharing.
#org.gradle.console=rich

# Use results of the first build during the configuration phase if the build environment remains unchanged,
# which will quickly entering the execution phase and accelerating the overall build process.
# Feel free to disable (comment) it if something go wrong.
org.gradle.configuration-cache=true

# ###################
# Project & Mod Properties
# ###################
group=me.ctidy.mcmod.demo
mod_version=1.0.0

archives_base_name=ctidy-demo

mod_id=ctidydemo
mod_name=CTidy Demo

description=CTidy's demo (or template) mod in Forge env.

# Just as an example,
# does not apply to the template project itself,
# nor does it enforce the use of license by specific projects using the template.
license=LGPL-v3
credits=

author=Tidy-Bear

resourcepack_format=15
datapack_format=15

# ###################
# MC & Mod Loader Properties
# ###################
java_version=17
minecraft_version=1.20.1

# https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.20.6
parchment_mappings_version=2024.06.16

mixin_version=0.8.5

# https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
# since 2024/06/03
forge_version=1.20.1-47.3.0

# ###################
# (Dev) runtime dependency variants
# ###################
# jei, rei or none (lower case)
runtime_variants_enough_items=jei

# jade, wthit, top or none (lower case)
runtime_variants_looking_tooltip=jade

# ###################
# Other build dependencies
# ###################
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
jei_artifact_id=jei-1.20.1
jei_version=15.20.0.105

# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# since 2024/02/26
# 7.0.66
architectury_version=9.2.14
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# since 2024/09/17
# 9.0.94
cloth_config_version=11.1.136
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# since 2024/10/26
rei_version=12.1.785

# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 11.12.3 since 2025/01/20
jade_version=5876199

# https://www.curseforge.com/minecraft/mc-mods/badpackets/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# https://maven4.bai.lol/lol/bai/badpackets/
# since 2023/10/06
badpackets_version=0.4.3
# https://www.curseforge.com/minecraft/mc-mods/wthit-forge/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# https://maven4.bai.lol/mcp/mobius/waila/wthit/
# since 2025/01/22
wthit_version=8.16.1

# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 10.0.3 since 2025/01/21
top_version=6106996

# https://www.curseforge.com/minecraft/mc-mods/catalogue/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 1.8.0 since 2023/09/24
catalogue_version=4766090

# https://www.curseforge.com/minecraft/mc-mods/configured/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 2.2.3 2024/05/14
configured_version=5180900

# https://www.curseforge.com/minecraft/mc-mods/searchables/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 1.0.3 since 2024/04/23
searchables_version=5284015

# https://www.curseforge.com/minecraft/mc-mods/controlling/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 12.0.2 since 2023/07/16
controlling_version=4646682

# https://www.curseforge.com/minecraft/mc-mods/spark/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 1.10.53 since 2023/09/05
spark_version=4738952

# https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 25.1.0 since 2025/02/12
xaerominimap_version=6184430

# https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
# 1.39.4 since 2025/02/20
xaeroworldmap_version=6212636

# ###################
# Game dependencies
# ###################
minecraft_request=[1.20.1,1.21)
fml_request=[47,)
forge_request=[47,)
